### ISSUE TITLE
Broken Links

### ISSUE THREAD

**Issue by snotskie** [dsalo/LocalPrivacy#1]
The following links have 404 issues or other issues as noted

- [Setting up FileVault](https://support.apple.com/kb/PH25553?viewlocale=en_US&locale=en_US)
- [AnyConnect](https://kb.wisc.edu/page.php?id=9120)
- [Connecting through Native VPN](https://kb.wisc.edu/page.php?id=12534) and [WiscVPN AnyConnect client ](https://kb.wisc.edu/page.php?id=11997) both 404 once you click the referenced [https://wiscvpn.doit.wisc.edu](https://wiscvpn.doit.wisc.edu) link.
- [Chrome](https://ajarr.org/home/security-recommendations/item/57-google-chrome-browser-settings) redirects to the site homepage
- [Using mobile phones as securely as possible](https://securityinabox.org/en/guide/mobile-phones)
- [iPhone, iPod Touch, iPad](https://kb.wisc.edu/page.php?id=38981) will 404 and then redirect to the correct page via js

**Comment by dsalo** [comment]
Thank you! Fixed, I hope.
